# Generated by Django 3.1.3 on 2022-12-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20221221_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text_question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='Enter a question', max_length=300),
        ),
    ]
