# Generated by Django 3.1.3 on 2023-01-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_remove_question_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text_question',
            new_name='question',
        ),
    ]
